### ISSUE TITLE
Logout/Delete Account issue

### ISSUE THREAD

**Issue by michellehardin** [emmaewade/Methods_Project#8]
It gives me this error if I just login and then try to immediately logout

Traceback (most recent call last):

  File "C:\Users\amhar\Downloads\Methods_Project-main (1)\Methods_Project-main\main.py", line 49, in <module>
    customer.Logout()

  File "C:\Users\amhar\Downloads\Methods_Project-main (1)\Methods_Project-main\Customer.py", line 51, in Logout
    exit()

NameError: name 'exit' is not defined

**Comment by michellehardin** [comment]
It also gives me this error if I try to login and delete account. But it does delete the account so that when you run it the next time, you have to re-register!

**Comment by AbnormalDistribution99** [comment]
There's no error when I try to do these things 
Can you try to pull it again so that you have the updated code.
